language: python
os: linux
dist: bionic
python:
  - "2.7"
  - "3.8"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y mesa-common-dev libxtst-dev libxt-dev libx11-xcb-dev libxcursor-dev libxrandr-dev libxinerama-dev;  fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxkbcommon-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libxkbcommon-x11-dev; fi

install:
  - pip install wheel
script:
  - python setup.py bdist_wheel
